### ISSUE TITLE
Check handlers as fast as we can

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/Asynchronous#3]
Currently the `PublishesUnhandledMessages` sends messages to the publisher when no handler is found inside the normal `command_bus`. Without the async bundle when no handler is defined you get the `NoHandlerForMessageName` exception but with it you are not getting this error. This is confusing because the async handler for me is not always running during development. Second problem is that the async RabbitMQ handler is also silently logging that there is no handler found. My suggestion would be to detect inside the `PublishesUnhandledMessages` if there is an async handler and if not still throw the exception.

**Comment by matthiasnoback** [comment]
@cmodijk The thing is, we don't know if we're in the same code base :) You could very well have a separate project in which the async handlers are registered and you can't check it from within the main application. I think that the way it currently works is the best option, but maybe you have some other ideas about it?

**Comment by cmodijk** [comment]
Hmm thats a great point. How would you handle thinks like that because the command class still needs to be in both projects right if there not than you can't deserialise them?

I will think about it if i come up with a different solution if not i'm closing this.

**Comment by matthiasnoback** [comment]
:) Thanks for bringing this up, and I may not be consistently handling this situation myself at all times. A shared code base may become a mess at some point, so it's good to at least consider the alternative of having separate code bases in this library.
