### ISSUE TITLE
Approach to process asynchronous messages using Amazon SQS?

### ISSUE THREAD

**Issue by holtkamp** [SimpleBus/Asynchronous#8]
Is anyone aware of an implementation for [Amazon SQS](https://aws.amazon.com/sqs/)? When investigating a bit, I did notice:

- there is a [SimpleBus/AsynchronousBundle](https://github.com/SimpleBus/AsynchronousBundle), that opens up [SimpleBus/Asynchronous](https://github.com/SimpleBus/Asynchronous) to Symfony
- there is a [SimpleBusBernardBundleBridge](https://github.com/SimpleBus/SimpleBusBernardBundleBridge), that bridges between the [SimpleBus/AsynchronousBundle](https://github.com/SimpleBus/AsynchronousBundle) and the [BernardBundle](https://github.com/bernardphp/BernardBundle)
- the [BernardBundle](https://github.com/bernardphp/BernardBundle) opens up [Bernard](https://github.com/bernardphp/bernard) functionality
- [Bernard](https://github.com/bernardphp/bernard) has an [Amazon SQS Driver](http://bernard.readthedocs.io/drivers.html#amazon-sqs)

Well, this all seems nice to investigate, but introduces a lot of bridging, dependencies, etc. The advantage might be that [Bernard](https://github.com/bernardphp/bernard) has various other [drivers](http://bernard.readthedocs.io/drivers.html), so switching to a different Queue provider should be easier (but hey, how often does that happen?). 

What would you guys advice? Go with the aforementioned approach, or create a [Amazon SQS](https://aws.amazon.com/sqs/) implementation for [SimpleBus/Asynchronous](https://github.com/SimpleBus/Asynchronous)?

**Comment by cmodijk** [comment]
@holtkamp Thank you for taking the time to create an issue. I'm currently using the RabbitMQ integration and i'm not using the `BernardBundle`. But if i check the implementation path there we have al the same steps to integrate to a Asynchronous driver. 

If you ask me to implement the Amazone SQL driver i will use the `BernardBundle` integration because it is already out there and battle tested by other users in production. The only reason for me to switch to an custom implementation would be if Amazon SQS has a feature that is not implemented by Bernard that i really want to use.

**Comment by holtkamp** [comment]
thanks for the response @cmodijk! Indeed, it seems the ```BernardBundle``` approach is the right one. Will do some experiments and report back here. Closing issue for now!

**Comment by cmodijk** [comment]
@holtkamp No problem, please let me know how it goes i have never used Amazon SQS and i'm interested in your experience.

**Comment by holtkamp** [comment]
@cmodijk it took some puzzling and configuration since I wanted this to work in a non-Symfony application, but I got it working. Publishing messages to SQS was quite easy. Consuming them takes some more work. Approach:

- configure 2 instances of a MessageBus
 - a "synchronous" / normal one that will handle Commands / Events
 - an "asynchronous" one that will publish Commands / Events to SQS

The consuming part took me some time to understand since I did not want to use the ```bernard:consume``` Symfony command, at that point the documentation might be improved a bit (how to actually consume (fetch + process) the messages stored at SQS. 

General idea:

```php
$queueName = 'MyQueueWithoutDots'; //no dots allowed in Amazon SQS!
$queueFactory  = $container->get(\Bernard\QueueFactory\PersistentFactory::class);
/* @var \Bernard\Queue $queue */
$queue = $queueFactory->create($queueName);

/* @var \SimpleBus\BernardBundleBridge\BernardConsumer */
$consumer = $container->get(\SimpleBus\BernardBundleBridge\BernardConsumer::class);

while($aSerializedEnvelope = $queue->dequeue()) {
            $consumer($aSerializedEnvelope->getMessage()); //Have  the consumer "consume" the message, this will re-publish the message from the asynchronous bus to the synchronous one
            $queue->acknowledge($aSerializedEnvelope); //Mark the Message as 'consumed'
}

**Comment by cmodijk** [comment]
@holtkamp If you have any suggestions on how we could make our docs better i would like to here your suggestions on our work in progress repo https://github.com/SimpleBus/docs. Maybe we could add a doc with your use case and documentation on how you solved the implementation with Amazone SQS.

**Comment by holtkamp** [comment]
Ok, will consider it to supply a 'non-Symfony' example. Problem (as always) is time / prios... Maybe an example project would by better, due to the load of configuration that needs to take place?

**Comment by holtkamp** [comment]
Ok, tried to come up with the "simplest" approach I can think of:

https://github.com/holtkamp/simplebus-asynchronous-bernard-sqs

Documenting this in an understandable way (especially the DIC configuration) would take a significant amount of time, which I currently lack...

**Comment by cmodijk** [comment]
@holtkamp Tnx for the example repository should we include this in the SimpleBus organisation for documentation purpose?

**Comment by holtkamp** [comment]
@cmodijk welcome, it is quite techy though... You can follow the general idea? Also tested it to ensure it works for newcomers?
